CREATE OR REPLACE FUNCTION INSERIR(P_TABELA TEXT, VARIADIC P_VALORES TEXT[]) RETURNS VOID AS $$
DECLARE
    VALORES TEXT;
    F_SQL TEXT;
BEGIN 
    SELECT STRING_AGG(QUOTE_NULLABLE(UPPER(VAL)), ', ') INTO VALORES FROM UNNEST(P_VALORES) AS VAL;

	CASE LOWER(P_TABELA)
		WHEN 'categoria' THEN
			F_SQL := FORMAT('INSERT INTO CATEGORIA(NOME) VALUES (%s)', VALORES);
		WHEN 'produto' THEN 
			F_SQL := FORMAT('INSERT INTO PRODUTO(NOME, DESCRICAO, VALOR, ID_CAT, ID_MARCA) VALUES (%s)', VALORES);
		WHEN 'marca' THEN
			F_SQL := FORMAT('INSERT INTO MARCA(NOME) VALUES (%s)', VALORES);
		WHEN 'mercado' THEN
			F_SQL := FORMAT('INSERT INTO MERCADO(CNPJ, LOGRADOURO, NUM, BAIRRO, CIDADE, ESTADO) VALUES (%s)', VALORES);
		ELSE
			RAISE EXCEPTION 'Não existe nenhuma tabela com o nome %.', P_TABELA;
	END CASE;
	EXECUTE F_SQL;
	RAISE NOTICE 'INSERÇÃO NA TABELA % FEITA COM SUCESSO!', P_TABELA;
	
	EXCEPTION
		WHEN SQLSTATE '22001' THEN
			RAISE EXCEPTION 'O nome fornecido excede a quantidade máxima de caracteres permitidos.';
		WHEN OTHERS THEN
			RAISE EXCEPTION 'Não foi possível fazer a inserção na tabela %. ERRO: %', P_TABELA, SQLERRM
			USING HINT = 'Cheque a ordem e a quantidade dos parâmetros.OBS.: IDs são serial.';
END;
$$ LANGUAGE PLPGSQL;

---------------------------
--       TESTES          --
---------------------------
SELECT INSERIR('categoria', 'frios');
SELECT INSERIR('categoria', 'FRIOS');
SELECT INSERIR('categoria', null);
SELECT INSERIR('produto', 'farinha de trigo', '    ', '10.50', null, null);

SELECT INSERIR('MARCA', 'MOLECA');
SELECT INSERIR('MARCA', 'ZAXY');
SELECT INSERIR('MARCA', 'LEOELEO');
SELECT INSERIR('MARCA', 'SAMSUNG');

SELECT INSERIR('MARCA', '     ');
SELECT INSERIR('MARCA', '');

SELECT INSERIR('categoria', '');

SELECT INSERIR('mercado', '1234567800019', 'Avenida Paulista', '1578', 'Bela Vista', 'São Paulo', 'SP');
SELECT ATUALIZAR('mercado', '1', 'num', '6', 'cidade', 'Teresina');

SELECT ATUALIZAR('categoria', '5', 'nome', 'null');

select * from categoria;
select * from produto;
select * from MARCA;
SELECT * FROM MERCADO;


--------------------------------------------------------------------------------------------------------------


CREATE OR REPLACE FUNCTION ATUALIZAR(P_TABELA TEXT, P_ID INT, VARIADIC P_PARAMETROS TEXT[]) RETURNS VOID AS $$
DECLARE
	ID_TABELA TEXT;
	F_SQL TEXT;
BEGIN
	IF ARRAY_LENGTH(P_PARAMETROS, 1) % 2 != 0 THEN
		RAISE EXCEPTION 'OS PARÂMETROS DEVEM SER PASSADOS EM PARES (COLUNA E VALOR).';
	END IF;

	IF NOT EXISTS (
		SELECT 1
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_SCHEMA = 'public' 
		AND TABLE_NAME = LOWER(P_TABELA)
	) THEN
		RAISE EXCEPTION 'A TABELA "%" NÃO EXISTE.', P_TABELA;
	END IF;

	P_TABELA := LOWER(P_TABELA);

	SELECT column_name INTO ID_TABELA
	FROM information_schema.columns
	WHERE table_name = P_TABELA
	ORDER BY ordinal_position LIMIT 1;

	PERFORM VALIDAR_ID(P_TABELA, ID_TABELA, P_ID);

	FOR I IN 1 .. (ARRAY_LENGTH(P_PARAMETROS, 1) - 1) BY 2 LOOP
        F_SQL := FORMAT('UPDATE %I SET %I = %L WHERE %I = $1', 
                        LOWER(P_TABELA), LOWER(P_PARAMETROS[I]), 
                        UPPER(P_PARAMETROS[I+1]), ID_TABELA);   
        EXECUTE F_SQL USING P_ID;
	END LOOP;
	RAISE NOTICE 'ATUALIZAÇÃO NA TABELA % FEITA COM SUCESSO!', P_TABELA;


	EXCEPTION
		WHEN SQLSTATE '22001' THEN
			RAISE EXCEPTION 'O nome fornecido excede a quantidade máxima de caracteres permitidos.';
		WHEN OTHERS THEN
			RAISE EXCEPTION 'Não foi possível fazer a atualização na tabela %. ERRO: %', P_TABELA, SQLERRM
			USING HINT = '
			Ordem dos parâmetros: nome da tabela, id do registro 
			e nome(s) da(s) coluna(s) e valor(es) que quer alterar respectivamente.';
END;
$$ LANGUAGE PLPGSQL;

SELECT ATUALIZAR('CATEGORIA', 2, 'NOME', 'TESTE');


------------------------------------------------------------------------------------------------------------


CREATE OR REPLACE FUNCTION DELETAR(TABELA TEXT, DADOS JSONB) RETURNS VOID AS $$
DECLARE
	F_SQL TEXT;
	F_CONDICOES TEXT;
	CAMPO RECORD;	
BEGIN
	-- V_DADOS := (SELECT JSONB_OBJECT_AGG(KEY, TO_JSONB(UPPER(VALUE #>> '{}'))) FROM JSONB_EACH(DADOS));

	PERFORM VALIDAR_NULOS(DADOS, TABELA);
	
	F_CONDICOES := '';
	FOR CAMPO IN SELECT * FROM JSONB_EACH(DADOS)
	LOOP
		IF EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = TABELA AND COLUMN_NAME = CAMPO.KEY) THEN
			F_CONDICOES := F_CONDICOES || FORMAT('AND %I = %L ', LOWER(CAMPO.KEY), UPPER(CAMPO.VALUE #>> '{}'));
		ELSE
			RAISE EXCEPTION 'A coluna "%" informada não existe na tabela "%".', CAMPO.KEY, TABELA;
		END IF;

	END LOOP;
	   
	F_SQL := FORMAT('UPDATE %I SET ativo = FALSE WHERE 1=1 ', LOWER(TABELA)) || F_CONDICOES;
	RAISE NOTICE 'SQL GERADO: %', f_sql;

	EXECUTE F_SQL;
	RAISE NOTICE 'Deleção do valor "%" da tabela "%" realizada com sucesso!', DADOS, TABELA;
END;
$$ LANGUAGE PLPGSQL;

SELECT DELETAR('CLIENTE', '{"id_marca": "1"}'::jsonb)
SELECT DELETAR('MARCA', '{"NOME": "LEOELEO"}'::jsonb)
SELECT DELETAR('MARCA', '{"nome": "LEOELEO"}'::jsonb)
SELECT DELETAR('MARCA', '{"NOME": "leoeleo"}'::jsonb)
SELECT DELETAR('MARCA', '{"nome": "samsung"}'::jsonb)

SELECT DELETAR('MARCA', '{"IDADE": null}'::jsonb)
SELECT * FROM CATEGORIA
SELECT * FROM MARCA
SELECT column_name FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='categoria'

-------------------------------------------------------------------------------------------------------


CREATE OR REPLACE FUNCTION BUSCAR_PELO_NOME(P_NOME VARCHAR, TABELA TEXT) RETURNS SETOF RECORD AS $$
DECLARE 
	F_QUERY TEXT := FORMAT('SELECT * FROM %I WHERE NOME ILIKE $1', LOWER(TABELA));

BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_SCHEMA = 'public' 
			AND TABLE_NAME = LOWER(TABELA)
	) THEN
		RAISE EXCEPTION 'A TABELA "%" NÃO EXISTE.', TABELA;
	END IF;
	
	IF NOT EXISTS (
		SELECT 1
		FROM INFORMATION_SCHEMA.COLUMNS
		WHERE TABLE_SCHEMA = 'public' 
			AND TABLE_NAME = LOWER(TABELA)
			AND COLUMN_NAME = 'nome' 
	) THEN
		RAISE EXCEPTION 'NÃO EXISTE COLUNA "NOME" NA TABELA "%".', TABELA;
	END IF;
	
	RETURN QUERY EXECUTE F_QUERY USING P_NOME;

	IF NOT FOUND THEN
		RAISE EXCEPTION 'NÃO EXISTE NENHUM REGISTRO NA TABELA % COM O NOME "%"', TABELA, P_NOME;
	END IF;

	EXCEPTION
		WHEN OTHERS THEN
			RAISE EXCEPTION 'NÃO FOI POSSÍVEL COMPLETAR A BUSCA. ERRO: %', SQLERRM;
END;
$$ LANGUAGE PLPGSQL;

SELECT * FROM BUSCAR_PELO_NOME('teste', 'categoria') AS (ID_CAT INT, NOME VARCHAR, ATIVO BOOLEAN);
SELECT * FROM BUSCAR_PELO_NOME('MOLECA', 'MARCA') AS (ID_MARCA INT, NOME VARCHAR, ATIVO BOOLEAN);
SELECT * FROM BUSCAR_PELO_NOME('', 'MARCA') AS (ID_MARCA INT, NOME VARCHAR, ATIVO BOOLEAN);
