CREATE OR REPLACE FUNCTION INSERIR(P_TABELA TEXT, VARIADIC P_VALORES TEXT[]) RETURNS VOID AS $$
DECLARE
    VALORES TEXT;
    F_SQL TEXT;
BEGIN 
    SELECT STRING_AGG(QUOTE_NULLABLE(VAL), ', ') INTO VALORES FROM UNNEST(P_VALORES) AS VAL;

	CASE LOWER(P_TABELA)
		WHEN 'categoria' THEN
			F_SQL := FORMAT('INSERT INTO CATEGORIA(NOME) VALUES (%s)', VALORES);
		WHEN 'produto' THEN 
			F_SQL := FORMAT('INSERT INTO PRODUTO(NOME, DESCRICAO, VALOR, ID_CAT, ID_MARCA) VALUES (%s)', VALORES);
		ELSE
			RAISE EXCEPTION 'Não existe nenhuma tabela com o nome %.', P_TABELA;
	END CASE;
	EXECUTE F_SQL;
	
	-- EXCEPTION
	-- 	WHEN SQLSTATE '22001' THEN
	-- 		RAISE NOTICE 'O nome fornecido excede a quantidade máxima de caracteres permitidos.';
	-- 	WHEN OTHERS THEN
	-- 		RAISE EXCEPTION 'Não foi possível fazer a inserção na tabela %. ERRO: %', P_TABELA, SQLERRM
	-- 		USING HINT = 'Cheque a ordem e a quantidade dos parâmetros.OBS.: IDs são serial.';
END;
$$ LANGUAGE PLPGSQL;


SELECT INSERIR('categoria', 'frios');
SELECT INSERIR('produto', 'farinha de trigo', 'farinha descrição', null, null, null);
select * from categoria;
select * from produto;

-------------------------------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION BUSCAR_PELO_NOME(P_NOME VARCHAR, TABELA TEXT) RETURNS SETOF RECORD AS $$
DECLARE 
	F_QUERY TEXT := FORMAT('SELECT * FROM %I WHERE NOME ILIKE $1', LOWER(TABELA));

BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_SCHEMA = 'public' 
			AND TABLE_NAME = LOWER(TABELA)
	) THEN
		RAISE EXCEPTION 'A TABELA "%" NÃO EXISTE.', TABELA;

	END IF;
	
	IF NOT EXISTS (
		SELECT 1
		FROM INFORMATION_SCHEMA.COLUMNS
		WHERE TABLE_SCHEMA = 'public' 
			AND TABLE_NAME = LOWER(TABELA)
			AND COLUMN_NAME = 'nome' 
	) THEN
		RAISE EXCEPTION 'NÃO EXISTE COLUNA "NOME" NA TABELA "%".', TABELA;
	
	END IF;
	
	RETURN QUERY EXECUTE F_QUERY USING P_NOME;

	IF NOT FOUND THEN
		RAISE EXCEPTION 'NÃO EXISTE NENHUM REGISTRO NA TABELA % COM O NOME "%"', TABELA, P_NOME;
	END IF;

		EXCEPTION
			WHEN RAISE_EXCEPTION THEN
        		RAISE;
			WHEN OTHERS THEN
				RAISE EXCEPTION 'NÃO FOI POSSÍVEL COMPLETAR A BUSCA. ERRO: %', SQLERRM;
END;
$$ LANGUAGE PLPGSQL;

SELECT * FROM BUSCAR_PELO_NOME('MOLECA', 'MARCA') AS (ID_ITEM INT, NOME VARCHAR, DESCRICAO VARCHAR);