-- FUNÇÕES DE VALIDAÇÃO QUE USAREMOS NOS TRIGGERS ANTES DE INSERIR NAS TABELAS

CREATE OR REPLACE FUNCTION VALIDAR_NULOS(REGISTRO ANYELEMENT, TABELA TEXT) RETURNS VOID AS $$
DECLARE 
	CAMPO RECORD;
BEGIN
	FOR CAMPO IN 
		SELECT * FROM JSONB_EACH(TO_JSONB(REGISTRO))
	LOOP
		IF (SELECT IS_NULLABLE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = TABELA AND COLUMN_NAME = CAMPO.KEY) = 'NO' THEN
			IF CAMPO.VALUE IS NULL OR CAMPO.VALUE = 'null'::JSONB THEN
				RAISE EXCEPTION 'ERRO: O CAMPO % NÃO PODE SER NULO.', CAMPO.KEY;
			END IF;
		END IF;
	END LOOP;
END;
$$ LANGUAGE PLPGSQL;


CREATE OR REPLACE FUNCTION VALIDAR_VALOR_UNICO(TABELA VARCHAR, COLUNA VARCHAR, VALOR VARCHAR) RETURNS VOID AS $$
DECLARE
    EXISTE BOOLEAN;
BEGIN
    EXECUTE FORMAT('SELECT EXISTS (SELECT 1 FROM %I WHERE %I = $1)', LOWER(tabela), LOWER(coluna))
    INTO EXISTE USING VALOR;

    IF EXISTE THEN
        RAISE EXCEPTION
            'Já existe o valor "%" na coluna % da tabela %.', VALOR, COLUNA, TABELA;
    END IF;
END;
$$ LANGUAGE PLPGSQL;


CREATE OR REPLACE FUNCTION VALIDAR_CAMPO_VAZIO(CAMPO VARCHAR, VALOR VARCHAR) RETURNS VOID AS $$
BEGIN
	IF (VALOR IS NOT NULL) AND (TRIM(VALOR) = '') THEN
		RAISE EXCEPTION 'O campo "%" não pode conter apenas espaços.', CAMPO;
	END IF;
END;
$$ LANGUAGE PLPGSQL;

SELECT VALIDAR_VALOR_UNICO('categoria', 'nome', 'teste');

SELECT VALIDAR_CAMPO_VAZIO('nome', '     ');
SELECT VALIDAR_CAMPO_VAZIO('nome', '');