-- FUNÇÕES DE VALIDAÇÃO ÚTEIS E GENÉRICAS

CREATE OR REPLACE FUNCTION VALIDAR_NULOS_E_VAZIOS(REGISTRO ANYELEMENT, TABELA TEXT) RETURNS VOID AS $$
DECLARE 
	CAMPO RECORD;
BEGIN
	FOR CAMPO IN
		SELECT * FROM JSONB_EACH(TO_JSONB(REGISTRO))
	LOOP
		IF (SELECT IS_NULLABLE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = TABELA AND COLUMN_NAME = CAMPO.KEY) = 'NO' THEN
			IF CAMPO.VALUE = 'null'::JSONB THEN
				RAISE EXCEPTION 'O CAMPO % NÃO PODE SER NULO.', CAMPO.KEY;
			END IF;
		END IF;

		IF JSONB_TYPEOF(CAMPO.VALUE) = 'string' THEN
			IF TRIM(CAMPO.VALUE #>> '{}') = '' THEN
				RAISE EXCEPTION 'O CAMPO "%" NÃO PODE CONTER APENAS ESPAÇOS.', CAMPO.KEY;
			END IF;
			IF UPPER(TRIM(CAMPO.VALUE #>> '{}')) = 'NULL' THEN
				RAISE EXCEPTION 'O CAMPO "%" NÃO PODE CONTER A PALAVRA "null".', CAMPO.KEY;
			END IF;
		END IF;
	END LOOP;
END;
$$ LANGUAGE PLPGSQL;


CREATE OR REPLACE FUNCTION VALIDAR_VALOR_UNICO(TABELA VARCHAR, COLUNA VARCHAR, VALOR VARCHAR) RETURNS VOID AS $$
DECLARE
    EXISTE BOOLEAN;
BEGIN
    EXECUTE FORMAT('SELECT EXISTS (SELECT 1 FROM %I WHERE %I = $1 AND ATIVO = TRUE)', LOWER(tabela), LOWER(coluna))
    INTO EXISTE USING VALOR;

    IF EXISTE THEN
        RAISE EXCEPTION
            'JÁ EXISTE O VALOR "%" NA COLUNA % DA TABELA %.', VALOR, COLUNA, TABELA;
    END IF;
END;
$$ LANGUAGE PLPGSQL;


CREATE OR REPLACE FUNCTION VALIDAR_ID(P_TABELA TEXT, ID_TABELA TEXT, P_ID INT) RETURNS VOID AS $$
DECLARE
    EXISTE BOOLEAN;
BEGIN
	EXECUTE FORMAT('SELECT EXISTS(SELECT 1 FROM %I WHERE %I = $1 AND ATIVO = TRUE)', LOWER(P_TABELA), LOWER(ID_TABELA)) 
    INTO EXISTE USING P_ID;
	
    IF NOT EXISTE THEN
        RAISE EXCEPTION 'NÃO EXISTE UM REGISTRO COM O ID % NA TABELA %.', P_ID, P_TABELA;
    END IF;
END;
$$ LANGUAGE PLPGSQL;


CREATE OR REPLACE FUNCTION VALIDAR_CHAVE(CHAVE TEXT, TABELA TEXT) RETURNS VOID AS $$
DECLARE
	EXISTE BOOLEAN;
BEGIN
	EXECUTE FORMAT('SELECT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = %L AND COLUMN_NAME = %L)', LOWER(TABELA), LOWER(CHAVE))
	INTO EXISTE;

	IF NOT EXISTE THEN
		RAISE EXCEPTION 'A COLUNA "%" NÃO EXISTE NA TABELA "%".', LOWER(CHAVE), LOWER(TABELA);
	END IF;
END;
$$ LANGUAGE PLPGSQL;