CREATE OR REPLACE FUNCTION INSERIR(P_TABELA TEXT, VARIADIC P_VALORES TEXT[]) RETURNS INT AS $$
DECLARE
	ID_GERADO INT;
    VALORES TEXT;
    F_SQL TEXT;
	F_ID_PROD INT;
	F_ID_ESTQ INT;

	F_ID_CLI INT;
	F_ID_PAG INT;
BEGIN 
    SELECT STRING_AGG(QUOTE_NULLABLE(UPPER(VAL)), ', ') INTO VALORES FROM UNNEST(P_VALORES) AS VAL;
	CASE LOWER(P_TABELA)
		WHEN 'categoria' THEN
			F_SQL := FORMAT('INSERT INTO CATEGORIA(NOME) VALUES (%s)', VALORES);
		WHEN 'produto' THEN 
			F_SQL := FORMAT('INSERT INTO PRODUTO(NOME, DESCRICAO, VALOR, ID_CAT, ID_MARCA) VALUES (%s)', VALORES);
		WHEN 'marca' THEN
			F_SQL := FORMAT('INSERT INTO MARCA(NOME) VALUES (%s)', VALORES);
		WHEN 'mercado' THEN
			F_SQL := FORMAT('INSERT INTO MERCADO(CNPJ, LOGRADOURO, NUM, BAIRRO, CIDADE, ESTADO) VALUES (%s)', VALORES);
		WHEN 'estoque' THEN 
			SELECT ID_PRODUTO INTO F_ID_PROD FROM BUSCAR_PELO_NOME(P_VALORES[2], 'produto') AS (ID_PRODUTO INT, NOME VARCHAR, DESCRICAO VARCHAR, VALOR NUMERIC, ID_CAT INT, ID_MARCA INT, ATIVO BOOLEAN);
			VALORES := FORMAT('%L, %s, %L', UPPER(P_VALORES[1]), F_ID_PROD, UPPER(P_VALORES[3]));
			F_SQL := FORMAT('INSERT INTO ESTOQUE(ID_MERC, ID_PROD, QTD_ESTOQUE) VALUES (%s)', VALORES);
		WHEN 'cargo' THEN
			F_SQL := FORMAT('INSERT INTO CARGO(NOME, SALARIO) VALUES (%s)', VALORES);
		WHEN 'funcionario' THEN
			F_SQL := FORMAT('INSERT INTO FUNCIONARIO(NOME, CPF, DT_NASC, TELEFONE, ID_MERC, ID_CARGO) VALUES (%s)', VALORES);
		WHEN 'cliente' THEN 
			F_SQL := FORMAT('INSERT INTO CLIENTE(CPF, NOME) VALUES (%s)', VALORES);
		WHEN 'pagamento' THEN
			F_SQL := FORMAT('INSERT INTO PAGAMENTO(NOME) VALUES (%s)', VALORES);
		WHEN 'venda' THEN
			PERFORM PERMITIR_SOMENTE_NUMEROS('CPF', P_VALORES[1]);
			PERFORM PERMITIR_SOMENTE_CARAC_ALFA('NOME', P_VALORES[3]);

			SELECT ID_CLI INTO F_ID_CLI FROM CLIENTE WHERE CPF = P_VALORES[1];
			SELECT ID_PAG INTO F_ID_PAG FROM PAGAMENTO WHERE NOME = P_VALORES[3];

			IF F_ID_CLI IS NULL THEN
				RAISE EXCEPTION 'CPF "%" NÃO ESTÁ CADASTRADO NO SISTEMA.', P_VALORES[1];
			END IF;
			IF F_ID_PAG IS NULL THEN
				RAISE EXCEPTION 'METÓDO DE PAGAMENTO "%" NÃO ESTÁ CADASTRADO NO SISTEMA.', P_VALORES[3];
			END IF;

			VALORES := FORMAT('%L, %L, %L', F_ID_CLI, P_VALORES[2], F_ID_PAG);
			F_SQL := FORMAT('INSERT INTO VENDA(ID_CLI, ID_FUNC, ID_PAG) VALUES (%s) RETURNING ID_VENDA', VALORES);
		
		WHEN 'item_venda' THEN
			SELECT ID_PRODUTO INTO F_ID_PROD FROM BUSCAR_PELO_NOME(P_VALORES[2], 'PRODUTO') AS (ID_PRODUTO INT, NOME VARCHAR, DESCRICAO VARCHAR, VALOR NUMERIC, ID_CAT INT, ID_MARCA INT, ATIVO BOOLEAN);
			SELECT ID_ESTOQUE INTO F_ID_ESTQ FROM ESTOQUE WHERE ID_MERC = P_VALORES[1]::INT AND ID_PROD = F_ID_PROD;

			IF F_ID_ESTQ IS NULL THEN
				RAISE EXCEPTION 'O PRODUTO "%" NÃO EXISTE NO ESTOQUE DO MERCADO DE ID "%".', P_VALORES[2], P_VALORES[1];
			END IF;
			
			VALORES := FORMAT('%L, %L, %L', F_ID_ESTQ, P_VALORES[3], P_VALORES[4]);
			F_SQL := FORMAT('INSERT INTO ITEM_VENDA (ID_ESTOQUE, ID_VENDA, QTD_VENDIDA) VALUES (%s) 
							ON CONFLICT (ID_VENDA, ID_ESTOQUE)
    						DO UPDATE SET QTD_VENDIDA = ITEM_VENDA.QTD_VENDIDA + EXCLUDED.QTD_VENDIDA', VALORES);
		ELSE
			RAISE EXCEPTION 'Não existe nenhuma tabela com o nome %.', P_TABELA;
	END CASE;
	
	IF F_SQL ILIKE '%RETURNING%' THEN
		EXECUTE F_SQL INTO ID_GERADO;
	ELSE
		EXECUTE F_SQL;
		ID_GERADO := NULL;
	END IF;
		
	RAISE NOTICE 'INSERÇÃO NA TABELA % FEITA COM SUCESSO!', P_TABELA;
	RETURN ID_GERADO;
		
	EXCEPTION
		WHEN SQLSTATE '22001' THEN
			RAISE EXCEPTION 'O nome fornecido excede a quantidade máxima de caracteres permitidos.';
		WHEN SQLSTATE '22P02' THEN
			RAISE EXCEPTION 'VALOR PASSADO É INVÁLIDO PARA A RESPECTIVA CONVERSÃO';
		WHEN OTHERS THEN
			RAISE EXCEPTION 'Não foi possível fazer a inserção na tabela %. ERRO: %', P_TABELA, SQLERRM
			USING HINT = 'Cheque a ordem e a quantidade dos parâmetros.OBS.: IDs são serial.';
END;
$$ LANGUAGE PLPGSQL;

---------------------------
--       TESTES          --
---------------------------
SELECT INSERIR('categoria', 'frios');
SELECT INSERIR('categoria', 'FRIOS');
SELECT INSERIR('categoria', '');
SELECT INSERIR('categoria', null);

SELECT INSERIR('MARCA', 'MOLECA');
SELECT INSERIR('MARCA', 'ZAXY');
SELECT INSERIR('MARCA', 'LEOELEO');
SELECT INSERIR('MARCA', 'SAMSUNG');
SELECT INSERIR('MARCA', '     ');
SELECT INSERIR('MARCA', '');

SELECT INSERIR('produto', 'farinha de trigo', null, '10.50', null, null);
SELECT INSERIR('produto', 'macarrão', 'macarrão de lasanha', '10.50', null, null);

SELECT INSERIR('PAGAMENTO', 'DÉBITO');
SELECT INSERIR('PAGAMENTO', 'DEBITO'); -- ACENTO DIFERENCIA PALAVRAS IGUAIS / TENTEI ADICIONAR UNACCENT MAS NÃO É UMA EXTENSÃO PADRÃO, PRECISA DE INSTALAÇÃO

SELECT INSERIR('mercado', '1234567800019', 'Avenida Paulista', '1578', 'Bela Vista', 'São Paulo', 'SP');

SELECT INSERIR('estoque', '1', 'farinha de trigo', '3');
SELECT INSERIR('estoque', '1', 'macarrão', '3');

SELECT INSERIR('CARGO', 'SUPERVISOR DE FROTA', '2500');

SELECT INSERIR('FUNCIONARIO', 'ALEXA','0889', '2006-04-03', '86988574021', '1', '1');

SELECT INSERIR('CLIENTE', '987', 'A1MANDA');

SELECT INSERIR('VENDA', '1', '7', '12');
SELECT INSERIR('VENDA', '3', '7', '12');

SELECT INSERIR('VENDA', '077', '7', 'DÉBITO');

SELECT INSERIR('ITEM_VENDA', '1', 'MACARRÃO', '1', '1');
SELECT INSERIR('ITEM_VENDA', '1', 'FARINHA DE TRIGO', '1', '1')
SELECT INSERIR('ITEM_VENDA', '1', 'FARINHA DE TRIGO', '1', '1')


SELECT ATUALIZAR('estoque', '1', 'qtd_estoque', '3');
SELECT ATUALIZAR('mercado', '1', 'num', '6', 'cidade', 'Teresina');
SELECT ATUALIZAR('categoria', '5', 'nome', 'null');
SELECT ATUALIZAR('produto', '20', 'ativo', 'false');

select * from categoria;
select * from produto;
select * from MARCA;
SELECT * FROM MERCADO;
SELECT * FROM ESTOQUE;
SELECT * FROM CARGO;
SELECT * FROM FUNCIONARIO;
SELECT * FROM CLIENTE;
SELECT * FROM VENDA;
SELECT * FROM PAGAMENTO;
SELECT * FROM ITEM_VENDA;


--------------------------------------------------------------------------------------------------------------


CREATE OR REPLACE FUNCTION ATUALIZAR(P_TABELA TEXT, P_ID INT, VARIADIC P_PARAMETROS TEXT[]) RETURNS VOID AS $$
DECLARE
	ID_TABELA TEXT;
	F_SQL TEXT;
BEGIN
	IF ARRAY_LENGTH(P_PARAMETROS, 1) % 2 != 0 THEN
		RAISE EXCEPTION 'OS PARÂMETROS DEVEM SER PASSADOS EM PARES (COLUNA E VALOR).';
	END IF;

	IF NOT EXISTS (
		SELECT 1
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_SCHEMA = 'public' 
		AND TABLE_NAME = LOWER(P_TABELA)
	) THEN
		RAISE EXCEPTION 'A TABELA "%" NÃO EXISTE.', P_TABELA;
	END IF;

	P_TABELA := LOWER(P_TABELA);

	SELECT column_name INTO ID_TABELA
	FROM information_schema.columns
	WHERE table_name = P_TABELA
	ORDER BY ordinal_position LIMIT 1;

	PERFORM VALIDAR_ID(P_TABELA, ID_TABELA, P_ID);

	FOR I IN 1 .. (ARRAY_LENGTH(P_PARAMETROS, 1) - 1) BY 2 LOOP
        F_SQL := FORMAT('UPDATE %I SET %I = %L WHERE %I = $1', 
                        LOWER(P_TABELA), LOWER(P_PARAMETROS[I]), 
                        UPPER(P_PARAMETROS[I+1]), ID_TABELA);   
        EXECUTE F_SQL USING P_ID;
	END LOOP;
	RAISE NOTICE 'ATUALIZAÇÃO NA TABELA % FEITA COM SUCESSO!', P_TABELA;


	EXCEPTION
		WHEN SQLSTATE '22001' THEN
			RAISE EXCEPTION 'O nome fornecido excede a quantidade máxima de caracteres permitidos.';
		WHEN OTHERS THEN
			RAISE EXCEPTION 'Não foi possível fazer a atualização na tabela %. ERRO: %', P_TABELA, SQLERRM
			USING HINT = '
			Ordem dos parâmetros: nome da tabela, id do registro 
			e nome(s) da(s) coluna(s) e valor(es) que quer alterar respectivamente.';
END;
$$ LANGUAGE PLPGSQL;

SELECT ATUALIZAR('CATEGORIA', 2, 'NOME', 'TESTE');


------------------------------------------------------------------------------------------------------------


CREATE OR REPLACE FUNCTION DELETAR(TABELA TEXT, DADOS JSONB) RETURNS VOID AS $$
DECLARE
	F_SQL TEXT;
	F_LINHAS TEXT;
	QTD_LINHAS INT;
	F_CONDICOES TEXT;
	CAMPO RECORD;	
BEGIN
	IF (SELECT COUNT(*) FROM JSONB_OBJECT_KEYS(DADOS)) = 0 THEN
		RAISE EXCEPTION 'NENHUM CRITÉRIO (CHAVE: COLUNA) FOI INFORMADO.';
	END IF;
	
	PERFORM VALIDAR_NULOS_E_VAZIOS(DADOS, TABELA);
	
	F_CONDICOES := '';
	FOR CAMPO IN SELECT * FROM JSONB_EACH(DADOS)
	LOOP
		PERFORM VALIDAR_CHAVE(CAMPO.KEY, TABELA);

		IF F_CONDICOES = '' THEN
			F_CONDICOES := FORMAT('%I = %L', LOWER(CAMPO.KEY), UPPER(CAMPO.VALUE #>> '{}'));
		ELSE	
			F_CONDICOES := F_CONDICOES || FORMAT(' AND %I = %L ', LOWER(CAMPO.KEY), UPPER(CAMPO.VALUE #>> '{}'));
		END IF;
	END LOOP;

	IF F_CONDICOES = '' THEN
		RAISE EXCEPTION 'NENHUMA CONDIÇÃO VÁLIDA FOI GERADA.';
	END IF;

	F_LINHAS := FORMAT('SELECT COUNT(*) FROM %I WHERE ATIVO = TRUE AND ', LOWER(TABELA)) || F_CONDICOES;
	EXECUTE F_LINHAS INTO QTD_LINHAS;
	IF QTD_LINHAS = 0 THEN
		RAISE EXCEPTION 'NÃO FOI ENCONTRADO NENHUM REGISTRO VÁLIDO COM AS INFORMAÇÕES PASSADAS.';
	END IF;

	F_SQL := FORMAT('UPDATE %I SET ativo = FALSE WHERE ', LOWER(TABELA)) || F_CONDICOES;
	EXECUTE F_SQL;
	
	RAISE NOTICE 'DELEÇÃO DA LINHA "%" DA TABELA "%" REALIZADA COM SUCESSO!', DADOS, TABELA;
END;
$$ LANGUAGE PLPGSQL;

SELECT DELETAR('CLIENTE', '{}'::jsonb)
SELECT DELETAR('MARCA', '{"NOME": "LEOELEO"}'::jsonb)
SELECT DELETAR('MARCA', '{"nome": "LEOELEO"}'::jsonb)
SELECT DELETAR('MARCA', '{"NOME": "leoeleo"}'::jsonb)
SELECT DELETAR('MARCA', '{"nome": "samsung"}'::jsonb)
SELECT DELETAR('MARCA', '{"nome": "ZAXY"}'::jsonb)
SELECT DELETAR('MARCA', '{"IDADE": null}'::jsonb)
SELECT DELETAR('PAGAMENTO', '{"NOME": "3"}'::JSONB);

SELECT * FROM CATEGORIA
SELECT * FROM MARCA
SELECT COUNT(*) FROM (SELECT * FROM MARCA)
UPDATE MARCA SET ATIVO = TRUE


-------------------------------------------------------------------------------------------------------


CREATE OR REPLACE FUNCTION BUSCAR_PELO_NOME(P_NOME VARCHAR, TABELA TEXT) RETURNS SETOF RECORD AS $$
DECLARE 
	F_QUERY TEXT := FORMAT('SELECT * FROM %I WHERE NOME ILIKE $1 AND ATIVO = TRUE', LOWER(TABELA));

BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_SCHEMA = 'public' 
			AND TABLE_NAME = LOWER(TABELA)
	) THEN
		RAISE EXCEPTION 'A TABELA "%" NÃO EXISTE.', TABELA;
	END IF;
	
	IF NOT EXISTS (
		SELECT 1
		FROM INFORMATION_SCHEMA.COLUMNS
		WHERE TABLE_SCHEMA = 'public' 
			AND TABLE_NAME = LOWER(TABELA)
			AND COLUMN_NAME = 'nome' 
	) THEN
		RAISE EXCEPTION 'NÃO EXISTE COLUNA "NOME" NA TABELA "%".', TABELA;
	END IF;
	
	RETURN QUERY EXECUTE F_QUERY USING P_NOME;

	IF NOT FOUND THEN
		RAISE EXCEPTION 'NÃO EXISTE NENHUM REGISTRO NA TABELA % COM O NOME "%"', TABELA, P_NOME;
	END IF;

	EXCEPTION
		WHEN OTHERS THEN
			RAISE EXCEPTION 'NÃO FOI POSSÍVEL COMPLETAR A BUSCA PELO NOME. ERRO: %', SQLERRM;
END;
$$ LANGUAGE PLPGSQL;

SELECT * FROM BUSCAR_PELO_NOME('teste', 'categoria') AS (ID_CAT INT, NOME VARCHAR, ATIVO BOOLEAN);
SELECT * FROM BUSCAR_PELO_NOME('MOLECA', 'MARCA') AS (ID_MARCA INT, NOME VARCHAR, ATIVO BOOLEAN);
SELECT * FROM BUSCAR_PELO_NOME('', 'MARCA') AS (ID_MARCA INT, NOME VARCHAR, ATIVO BOOLEAN);
SELECT * FROM BUSCAR_PELO_NOME('FARINHA DE TRIGO', 'produto') AS (ID_PRODUTO INT, NOME VARCHAR, DESCRICAO VARCHAR, VALOR NUMERIC, ID_CAT INT, ID_MARCA INT, ATIVO BOOLEAN);


-------------------------------------------------------------------------------------------------------


CREATE TYPE ITEM_VENDA AS (
	ID_MERC INT,
	NOME_PROD TEXT,
	ID_VENDA INT,
	QTD INT
)


CREATE OR REPLACE FUNCTION REALIZAR_VENDA(P_CPF_CLI TEXT, P_ID_MERC INT, P_ID_FUNC INT, P_TIPO_PG TEXT, P_ITENS ITEM_VENDA[]) RETURNS VOID AS $$
DECLARE
	ID_VENDA INT;
BEGIN
	ID_VENDA := SELECT INSERIR('VENDA', P_CPF_CLI, P_ID_FUNC, P_ID_MERC);

	FOREACH ITEM IN P_ITENS
	LOOP