CREATE TABLE CATEGORIA(
	ID_CAT SERIAL PRIMARY KEY,
	NOME VARCHAR(20) NOT NULL
);

CREATE TABLE MARCA(
	ID_MARCA SERIAL PRIMARY KEY,
	NOME VARCHAR(15) NOT NULL
);

CREATE TABLE PRODUTO(
	ID_PROD SERIAL PRIMARY KEY,
	NOME VARCHAR(30),
	DESCRICAO VARCHAR(70),
	VALOR FLOAT NOT NULL,
	ID_CAT INT REFERENCES CATEGORIA(ID_CAT),
	ID_MARCA INT REFERENCES MARCA(ID_MARCA)
);

CREATE TABLE MERCADO(
	ID_MERCADO SERIAL PRIMARY KEY,
	CNPJ VARCHAR(14) NOT NULL,
	LOGRADOURO VARCHAR(30) NOT NULL,
	NUM INT NOT NULL,
	BAIRRO VARCHAR(15) NOT NULL,
	CIDADE VARCHAR(15) NOT NULL,
	ESTADO VARCHAR(15) NOT NULL
);

CREATE TABLE ESTOQUE(
	ID_ESTOQUE SERIAL PRIMARY KEY,
	ID_MERC INT NOT NULL REFERENCES MERCADO(ID_MERCADO),
	ID_PROD INT NOT NULL REFERENCES PRODUTO(ID_PROD),
	QTD_ESTOQUE INT NOT NULL
);

CREATE TABLE CARGO(
	ID_CARGO SERIAL PRIMARY KEY,
	NOME VARCHAR(20) NOT NULL,
	SALARIO FLOAT NOT NULL
);

CREATE TABLE FUNCIONARIO(
	ID_FUNC SERIAL PRIMARY KEY,
	NOME VARCHAR(20) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	DT_NASC DATE NOT NULL,
	TELEFONE VARCHAR(11) NOT NULL,
	ID_MERC INT NOT NULL REFERENCES MERCADO(ID_MERCADO),
	ID_CARGO INT NOT NULL REFERENCES CARGO(ID_CARGO)
);

CREATE TABLE CLIENTE(
	ID_CLI SERIAL PRIMARY KEY,
	CPF VARCHAR(11) NOT NULL,
	NOME VARCHAR(20) NOT NULL
);

CREATE TABLE PAGAMENTO(
	ID_PAG SERIAL PRIMARY KEY,
	NOME VARCHAR(15) NOT NULL
);

CREATE TABLE VENDA(
	ID_VENDA SERIAL PRIMARY KEY,
	ID_CLI INT NOT NULL REFERENCES CLIENTE(ID_CLI),
	ID_FUNC INT NOT NULL REFERENCES FUNCIONARIO(ID_FUNC),
	ID_PAG INT NOT NULL REFERENCES PAGAMENTO(ID_PAG),
	VALOR_TOTAL FLOAT NOT NULL
);

CREATE TABLE ITEM_VENDA(
	ID_IV SERIAL PRIMARY KEY,
	ID_ESTOQUE INT NOT NULL REFERENCES ESTOQUE(ID_ESTOQUE),
	ID_VENDA INT NOT NULL REFERENCES VENDA(ID_VENDA),
	QTD_VENDIDA INT NOT NULL CHECK(QTD_VENDIDA > 0),
	VALOR_TOTAL_ITEM FLOAT NOT NULL
);