CREATE OR REPLACE FUNCTION VALIDAR_CATEGORIA() RETURNS TRIGGER AS $$
BEGIN
	PERFORM VALIDAR_NULOS(NEW, TG_TABLE_NAME);
	PERFORM VALIDAR_VALOR_UNICO('categoria', 'nome', NEW.NOME);
	PERFORM VALIDAR_CAMPO_VAZIO('nome', NEW.NOME);

	RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;


CREATE OR REPLACE FUNCTION VALIDAR_MARCA() RETURNS TRIGGER AS $$
BEGIN
	PERFORM VALIDAR_NULOS(NEW, TG_TABLE_NAME);
	PERFORM VALIDAR_VALOR_UNICO('marca', 'nome', NEW.NOME);
	PERFORM VALIDAR_CAMPO_VAZIO('marca', NEW.NOME);
		
	RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;


CREATE OR REPLACE TRIGGER INSERIR_CATEGORIA BEFORE INSERT ON CATEGORIA 
FOR EACH ROW EXECUTE PROCEDURE VALIDAR_CATEGORIA();

CREATE OR REPLACE TRIGGER INSERIR_MARCA BEFORE INSERT ON MARCA
FOR EACH ROW EXECUTE PROCEDURE VALIDAR_MARCA();