CREATE OR REPLACE FUNCTION VALIDAR_CATEGORIA() RETURNS TRIGGER AS $$
BEGIN
	PERFORM VALIDAR_NULOS_E_VAZIOS(NEW, TG_TABLE_NAME);
	PERFORM VALIDAR_VALOR_UNICO('categoria', 'nome', NEW.NOME);

	RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;


CREATE OR REPLACE FUNCTION VALIDAR_MARCA() RETURNS TRIGGER AS $$
BEGIN
	PERFORM VALIDAR_NULOS_E_VAZIOS(NEW, TG_TABLE_NAME);
	PERFORM VALIDAR_VALOR_UNICO('marca', 'nome', NEW.NOME);
		
	RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;


CREATE OR REPLACE FUNCTION VALIDAR_PRODUTO() RETURNS TRIGGER AS $$
BEGIN
	PERFORM VALIDAR_NULOS_E_VAZIOS(NEW, TG_TABLE_NAME);
	IF (NEW.VALOR < 0) THEN 
		RAISE EXCEPTION 'O VALOR DO PRODUTO NÃO PODE SER NEGATIVO.';
	END IF;

	IF (NEW.ID_CAT IS NOT NULL) THEN
		PERFORM VALIDAR_ID('categoria', 'id_cat', NEW.ID_CAT);
	END IF;
	IF (NEW.ID_MARCA IS NOT NULL) THEN
		PERFORM VALIDAR_ID('marca', 'id_marca', NEW.ID_MARCA);
	END IF;

	RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION VALIDAR_MERCADO() RETURNS TRIGGER AS $$
BEGIN
	PERFORM VALIDAR_NULOS_E_VAZIOS(NEW, TG_TABLE_NAME);
	IF (OLD.CNPJ != NEW.CNPJ) THEN
		PERFORM VALIDAR_VALOR_UNICO('mercado', 'cnpj', NEW.CNPJ);
	END IF;
	RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;


CREATE OR REPLACE TRIGGER INSERIR_CATEGORIA BEFORE INSERT OR UPDATE ON CATEGORIA 
FOR EACH ROW EXECUTE PROCEDURE VALIDAR_CATEGORIA();

CREATE OR REPLACE TRIGGER INSERIR_MARCA BEFORE INSERT OR UPDATE ON MARCA
FOR EACH ROW EXECUTE PROCEDURE VALIDAR_MARCA();

CREATE OR REPLACE TRIGGER INSERIR_PRODUTO BEFORE INSERT OR UPDATE ON PRODUTO
FOR EACH ROW EXECUTE PROCEDURE VALIDAR_PRODUTO();

CREATE OR REPLACE TRIGGER INSERIR_MERCADO BEFORE INSERT OR UPDATE ON MERCADO 
FOR EACH ROW EXECUTE PROCEDURE VALIDAR_MERCADO();