CREATE OR REPLACE FUNCTION VALIDAR_CATEGORIA() RETURNS TRIGGER AS $$
BEGIN
	PERFORM VALIDAR_NULOS(NEW);
	PERFORM VALIDAR_VALOR_UNICO('categoria', 'nome', NEW.NOME);

	RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE TRIGGER INSERIR_CATEGORIA BEFORE INSERT ON CATEGORIA 
FOR EACH ROW EXECUTE PROCEDURE VALIDAR_CATEGORIA();